name: outputs
on: [issue_comment, push]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: |
          echo "first job1 and first step"

  job2:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.output1 }}
      output2: ${{ steps.step2.outputs.output2 }}
    steps:
      - name: step1
        id: step1
        run: |
          date -Is > output1
          cat output1
          echo "output1=$(cat output1)" >> $GITHUB_OUTPUT
      - name: step2
        id: step2
        run: |
          cat /proc/sys/kernel/random/uuid > output2
          cat output2
          echo "output2=$(cat output2)" >> $GITHUB_OUTPUT

  job3:
    needs: [job1, job2]
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ needs.job2.outputs.output1 }}
      - run: echo ${{ needs.job2.outputs.output2 }}
      - run: echo ${{ needs.job2.result }}

  job4:
    needs: [job3]
    runs-on: ubuntu-latest
    steps:
      - run: echo "job4 !!!"
